"""
Razor-AI backend. Thin FastAPI layer that wires together:
- reconciliation.py  (deterministic matching -- no AI)
- explanations.py    (deterministic templates -- no AI)
- chatbot.py          (the ONLY AI component, Gemini-powered)
- database.py         (SQLite storage + audit trail)

Run locally:
    uvicorn main:app --reload --port 8000
Then visit http://localhost:8000/docs for interactive API docs (auto-generated by FastAPI).
"""

import os
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import pandas as pd

from reconciliation import reconcile, compute_metrics, evaluate_against_answer_key
from explainations import explain
from chatbot import ask
from database import init_db, log_audit, get_audit_trail, reset_db, get_db

app = FastAPI(title="Razor-AI Reconciliation API")

# CORS: allow_origins=["*"] is fine for local development and hackathon
# judging where the frontend URL isn't fixed yet. For a real production
# deployment this should be locked down to the exact frontend domain.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")

init_db()

# In-memory holders for the current batch, refreshed on /batch/load and
# /reconcile/run. Fine for a single-demo-instance prototype; a multi-user
# production version would key this by session or account instead.
_state = {"transactions": None, "reconciled": None, "answer_key": None}


# ---------- Request/response models ----------

class ChatRequest(BaseModel):
    question: str


# ---------- Batch endpoints ----------

@app.post("/batch/load")
def load_batch():
    """Loads the synthetic batch generated by data/generate_data.py."""
    batch_path = os.path.join(DATA_DIR, "synthetic_batch.csv")
    if not os.path.exists(batch_path):
        raise HTTPException(
            status_code=404,
            detail="No batch found. Run 'python generate_data.py' in the data/ folder first.",
        )

    df = pd.read_csv(batch_path, parse_dates=["created_at", "settled_at"])
    _state["transactions"] = df

    answer_key_path = os.path.join(DATA_DIR, "answer_key.csv")
    _state["answer_key"] = pd.read_csv(answer_key_path) if os.path.exists(answer_key_path) else None

    return {"loaded": len(df)}


@app.post("/reconcile/run")
def run_reconciliation():
    """Runs the deterministic reconciliation engine on the loaded batch and logs results to the audit trail."""
    if _state["transactions"] is None:
        raise HTTPException(status_code=400, detail="No batch loaded. Call /batch/load first.")

    reconciled = reconcile(_state["transactions"])
    _state["reconciled"] = reconciled

    for _, row in reconciled.iterrows():
        row_dict = row.to_dict()
        if row_dict["reconciliation_status"] == "exception":
            explanation = explain(row_dict)
            log_audit("exception", row_dict["payment_id"], explanation, "rule_engine")
        else:
            log_audit("match", row_dict["payment_id"], "Matched within tolerance", "rule_engine")

    metrics = compute_metrics(reconciled)

    # If we have the hidden answer key (demo/testing scenario), also return
    # measured accuracy -- this is what backs the "measured accuracy, not a
    # cherry-picked match" claim from the track brief.
    if _state["answer_key"] is not None:
        metrics["validation"] = evaluate_against_answer_key(reconciled, _state["answer_key"])

    return metrics


@app.get("/reconcile/metrics")
def get_metrics():
    if _state["reconciled"] is None:
        raise HTTPException(status_code=400, detail="Reconciliation has not been run yet.")
    return compute_metrics(_state["reconciled"])


@app.get("/reconcile/exceptions")
def get_exceptions():
    if _state["reconciled"] is None:
        raise HTTPException(status_code=400, detail="Reconciliation has not been run yet.")

    reconciled = _state["reconciled"]
    exceptions = reconciled[reconciled["reconciliation_status"] == "exception"]

    def clean(value):
        """
        Pandas leaves NaN in numeric columns for rows with no settlement
        (missing_settlement, duplicate_record). Python's json module cannot
        serialize NaN -- it must be converted to None (JSON null) before it
        reaches the response, or this endpoint crashes with a 500 error.
        """
        if pd.isna(value):
            return None
        return value

    result = []
    for _, row in exceptions.iterrows():
        row_dict = row.to_dict()
        result.append({
            "payment_id": row_dict["payment_id"],
            "mismatch_type": row_dict["mismatch_type"],
            "delta": clean(row_dict.get("delta")),
            "explanation": explain(row_dict),
        })
    return result


# ---------- Chatbot endpoint ----------

@app.post("/chat")
def chat(req: ChatRequest):
    if _state["reconciled"] is None:
        raise HTTPException(status_code=400, detail="Reconciliation has not been run yet.")

    result = ask(req.question, _state["reconciled"])
    log_audit("chat_query", "-", f"Q: {req.question} | A: {result['answer']}", "gemini_api")
    return result


# ---------- Audit trail ----------

@app.get("/audit-trail")
def audit_trail(limit: int = 100):
    return get_audit_trail(limit)


# ---------- Demo hygiene ----------

@app.post("/demo/reset")
def demo_reset():
    """
    Clears all state and the audit trail. Exists so one judge testing the
    live link doesn't leave behind data that confuses the next person --
    call this before or after a demo session.
    """
    _state["transactions"] = None
    _state["reconciled"] = None
    _state["answer_key"] = None
    reset_db()
    return {"status": "reset"}


@app.get("/")
def root():
    return {
        "service": "Razor-AI Reconciliation API",
        "docs": "/docs",
        "status": "ok",
    }
