export const TOUR_STEPS = [
  {
    id: 'dashboard-overview',
    section: 'Dashboard',
    title: 'Dashboard overview',
    body: 'Your Dashboard is the finance control center. It gives you a quick view of reconciliation performance, unresolved exposure, cash position and important finance activity.',
    tab: 'dashboard',
    page: 'home',
    target: 'dashboard-overview',
  },
  {
    id: 'dashboard-metrics',
    section: 'Dashboard',
    title: 'Reconciliation metrics',
    body: 'Match rate, records processed and amount matched come from the deterministic engine after a batch is reconciled — not from a generated score.',
    tab: 'dashboard',
    page: 'home',
    target: 'dashboard-metrics',
  },
  {
    id: 'dashboard-exceptions',
    section: 'Dashboard',
    title: 'Exception exposure',
    body: 'Open exceptions and amount at risk tell you what still needs a human. Missing settlements stay here; the engine will not invent a UTR.',
    tab: 'dashboard',
    page: 'home',
    target: 'dashboard-exceptions',
  },
  {
    id: 'dashboard-cash',
    section: 'Dashboard',
    title: 'Cash snapshot',
    body: 'This strip shows available cash, in-transit settlements, blocked exception amounts and the next 7-day inflow from the loaded batch.',
    tab: 'dashboard',
    page: 'home',
    target: 'dashboard-cash',
    skipIfMissing: true,
  },
  {
    id: 'dashboard-queue',
    section: 'Dashboard',
    title: 'Work queue',
    body: 'When a batch is reconciled, the controller ranks what to do next — high-value missing settlements, recurring clusters, GST mismatches — from live data. Click a row to open it.',
    tab: 'dashboard',
    page: 'home',
    target: 'dashboard-queue',
    skipIfMissing: true,
  },
  {
    id: 'payments-filter',
    section: 'Payments',
    title: 'Date and time filter',
    body: 'Use this filter to investigate payments from a specific period. You can choose a preset range or define a custom date/time range.',
    tab: 'dashboard',
    page: 'payments',
    target: 'payments-filter',
    waitFor: 'filter',
    tryPrompt: 'Try it: click a date preset such as Last 7 days.',
  },
  {
    id: 'payments-table',
    section: 'Payments',
    title: 'Payment records',
    body: 'Each payment contains the information needed to understand its status, settlement and reconciliation state. Exception rows open the exception queue. There is no separate details button — click the row.',
    tab: 'dashboard',
    page: 'payments',
    target: 'payments-table',
  },
  {
    id: 'exceptions-list',
    section: 'Exceptions',
    title: 'Exception queue',
    body: 'Exceptions are transactions that could not be confidently reconciled. Select a row to inspect evidence, fees, GST and suggested actions.',
    tab: 'dashboard',
    page: 'exceptions',
    target: 'exceptions-list',
    waitFor: 'click',
    tryPrompt: 'Try it: click an exception row in the table.',
  },
  {
    id: 'exceptions-filter',
    section: 'Exceptions',
    title: 'Filters',
    body: 'Search by payment ID or explanation, filter by mismatch type, and use the date range to focus the queue.',
    tab: 'dashboard',
    page: 'exceptions',
    target: 'exceptions-filter',
  },
  {
    id: 'exception-explain',
    section: 'Exceptions',
    title: 'Explain this difference',
    body: 'The Finance Controller investigates related records and explains the difference using evidence such as payment, settlement, fees, GST and refunds. This is a read-only waterfall — it does not change the books.',
    tab: 'dashboard',
    page: 'exceptions',
    target: 'exception-explain',
    waitFor: 'click',
    tryPrompt: 'Try it: click Explain this difference.',
    skipIfMissing: true,
  },
  {
    id: 'exception-resolve',
    section: 'Exceptions',
    title: 'Resolve — try this yourself',
    body: 'Apply suggested fix, waive and escalate actually mutate the batch. The tour will not click them. Try this yourself after you have reviewed the evidence.',
    tab: 'dashboard',
    page: 'exceptions',
    target: 'exception-resolve',
    skipIfMissing: true,
    lockTarget: true,
  },
  {
    id: 'cash-position',
    section: 'Cash',
    title: 'Cash position',
    body: 'Cash gives you a real-time view of available funds, pending settlements, unresolved exposure and projected position.',
    tab: 'dashboard',
    page: 'cash',
    target: 'cash-position',
  },
  {
    id: 'cash-why',
    section: 'Cash',
    title: 'Why is my cash different?',
    body: 'Use this to understand why expected cash and actual cash differ. The system traces the difference across payments, settlements, refunds, fees, GST and withdrawals. It only calculates — it does not move money.',
    tab: 'dashboard',
    page: 'cash',
    target: 'cash-why',
    skipIfMissing: true,
  },
  {
    id: 'gst-summary',
    section: 'GST',
    title: 'GST summary',
    body: 'Use GST to review tax-related financial activity and identify discrepancies between expected and recorded tax amounts. GST is 18% of the processing fee, not of GMV.',
    tab: 'dashboard',
    page: 'gst',
    target: 'gst-summary',
  },
  {
    id: 'gst-table',
    section: 'GST',
    title: 'Tax-line table',
    body: 'Mismatched lines can be opened in Exceptions. Nothing here is invented to make GST look clean.',
    tab: 'dashboard',
    page: 'gst',
    target: 'gst-table',
    skipIfMissing: true,
  },
  {
    id: 'withdraw-available',
    section: 'Withdraw',
    title: 'Available balance',
    body: 'This is the amount currently eligible for withdrawal. Previously withdrawn funds are excluded.',
    tab: 'dashboard',
    page: 'withdraw',
    target: 'withdraw-available',
  },
  {
    id: 'withdraw-date',
    section: 'Withdraw',
    title: 'Date filter',
    body: 'Use the date filter to calculate eligible earnings up to a specific date.',
    tab: 'dashboard',
    page: 'withdraw',
    target: 'withdraw-date',
    skipIfMissing: true,
  },
  {
    id: 'withdraw-amount',
    section: 'Withdraw',
    title: 'Withdrawal amount',
    body: 'Enter the amount you want to withdraw. Preview updates as you type. The tour will not submit a withdrawal.',
    tab: 'dashboard',
    page: 'withdraw',
    target: 'withdraw-amount',
    skipIfMissing: true,
  },
  {
    id: 'withdraw-analysis',
    section: 'Withdraw',
    title: 'Withdrawal analysis',
    body: 'Before confirming, the system breaks down the requested amount into applicable fees, tax, refunds and adjustments so you can see what you will actually receive.',
    tab: 'dashboard',
    page: 'withdraw',
    target: 'withdraw-analysis',
    skipIfMissing: true,
  },
  {
    id: 'withdraw-confirm',
    section: 'Withdraw',
    title: 'Confirm withdrawal — try this yourself',
    body: 'Confirming creates a synthetic withdrawal and updates cash. The tour will not press this. Try this yourself if you want to see the ledger change.',
    tab: 'dashboard',
    page: 'withdraw',
    target: 'withdraw-confirm',
    skipIfMissing: true,
    lockTarget: true,
  },
  {
    id: 'audit-filters',
    section: 'Audit logs',
    title: 'Audit filters',
    body: 'Use filters to find specific actions, records or time periods in the stored audit trail.',
    tab: 'dashboard',
    page: 'audit',
    target: 'audit-filters',
  },
  {
    id: 'audit-table',
    section: 'Audit logs',
    title: 'Audit history',
    body: 'Audit Logs provide the history of important system, AI and human actions. Click a row to inspect what happened, when it happened and which record was affected.',
    tab: 'dashboard',
    page: 'audit',
    target: 'audit-table',
  },
  {
    id: 'rules-purpose',
    section: 'Rules',
    title: 'What Rules is for',
    body: 'Rules is a notebook of human policy for investigators. It does not auto-fix exceptions, invent settlements, or change cash.',
    tab: 'dashboard',
    page: 'knowledge',
    target: 'rules-purpose',
  },
  {
    id: 'rules-form',
    section: 'Rules',
    title: 'Add a standing rule',
    body: 'Name the mismatch type and write what a human should check. The controller may quote this during investigation — it never posts a UTR.',
    tab: 'dashboard',
    page: 'knowledge',
    target: 'rules-form',
  },
  {
    id: 'rules-list',
    section: 'Rules',
    title: 'Saved rules',
    body: 'Enable, disable or delete rules here. Influence count shows how often investigation text quoted the rule.',
    tab: 'dashboard',
    page: 'knowledge',
    target: 'rules-list',
  },
  {
    id: 'reports-period',
    section: 'Reports',
    title: 'Earning analysis',
    body: 'Switch Overall, Monthly and Yearly to see GMV, GST and net settlement as charts from the active batch.',
    tab: 'dashboard',
    page: 'reports',
    target: 'reports-period',
    skipIfMissing: true,
  },
  {
    id: 'marketplace-store',
    section: 'Marketplace',
    title: 'Demo store checkout',
    body: 'Marketplace is the Northwind Goods demo store. A checkout creates a real payment in the same reconciliation batch. Flagged outcomes create controller notifications. Refunds from Past orders also post through the engine.',
    tab: 'merchant-checkout',
    page: 'store',
    target: 'marketplace-store',
  },
  {
    id: 'reconciliation-generate',
    section: 'Reconciliation',
    title: 'Generate Demo Dataset',
    body: 'Creates a synthetic finance batch that can be used to demonstrate the reconciliation workflow. The tour will not generate a batch for you.',
    tab: 'dashboard',
    page: 'reconciliation',
    target: 'reconciliation-generate',
    lockTarget: true,
  },
  {
    id: 'reconciliation-run',
    section: 'Reconciliation',
    title: 'Run reconciliation',
    body: 'Runs the reconciliation engine across the batch. Matching is deterministic. Gemini is only used for Q&A.',
    tab: 'dashboard',
    page: 'reconciliation',
    target: 'reconciliation-run',
    lockTarget: true,
  },
  {
    id: 'reconciliation-results',
    section: 'Reconciliation',
    title: 'Throughput, accuracy, honest exceptions',
    body: 'The system reports what it matched, what it could not resolve and where human attention is required — throughput, measured accuracy against a hidden answer key when present, and an honest exception list.',
    tab: 'dashboard',
    page: 'reconciliation',
    target: 'reconciliation-results',
  },
];

export const TOUR_SECTIONS = [...new Set(TOUR_STEPS.map((step) => step.section))];

export function firstStepIndexForPage(page, tab = 'dashboard') {
  if (tab === 'merchant-checkout') {
    const store = TOUR_STEPS.findIndex((step) => step.tab === 'merchant-checkout');
    return store >= 0 ? store : 0;
  }
  const index = TOUR_STEPS.findIndex((step) => step.page === page);
  return index >= 0 ? index : 0;
}

export const STORAGE_KEY = 'razorai-product-tour';
