export const LIFECYCLE_STAGES = [
  'Shop',
  'Payment',
  'Fee',
  'Refund',
  'Settlement',
  'Reconciliation',
  'Exception',
  'Investigation',
  'Resolution',
];

export const TOUR_STEPS = [
  {
    id: 'store-intro',
    section: 'Shop',
    lifecycle: 'Shop',
    title: 'Start in the shop — this is how money enters Razor-AI',
    body: 'Northwind Goods is a demo store, not a separate product. Every purchase you make here becomes a real payment row in the finance controller. The rest of the tour follows that rupee: capture, fee, refund, settlement, match, flag, investigate, then a human decision.',
    meaning: 'A merchant’s problem starts at checkout, not on a spreadsheet. If the controller never sees the live payment, reconciliation is just a file upload.',
    action: 'Stay on Marketplace. Next you will add a product, check out, and later find the same payment in the controller.',
    tab: 'merchant-checkout',
    view: 'store',
    page: 'store',
    target: 'store-intro',
  },
  {
    id: 'store-catalogue',
    section: 'Shop',
    lifecycle: 'Shop',
    title: 'Pick what the customer is buying',
    body: 'These products are the gross merchandise value (GMV). The price you see is goods value. Razorpay will later take a processing fee on that GMV, and GST on the fee — not another 18% on the product price in the controller.',
    meaning: 'Goods GST on the cart and processing-fee GST in the books are different. Mixing them is a common reason a settlement “looks short”.',
    action: 'Scan the catalogue. In the hands-on tour, add at least one item so checkout has an amount.',
    tab: 'merchant-checkout',
    view: 'store',
    page: 'store',
    target: 'store-catalogue',
  },
  {
    id: 'store-add',
    section: 'Shop',
    lifecycle: 'Shop',
    title: 'Add to cart',
    body: 'Quantity lives in the session cart. Nothing has been charged yet — there is no payment_id until you pay.',
    meaning: 'Until capture, finance has nothing to match. Abandoned carts do not create exceptions.',
    action: 'Add an item, then open the cart from the header.',
    tab: 'merchant-checkout',
    view: 'store',
    page: 'store',
    target: 'store-add',
    waitFor: 'click',
    tryPrompt: 'Try it: tap Add, then use − / + on the card.',
  },
  {
    id: 'store-cart-btn',
    section: 'Shop',
    lifecycle: 'Shop',
    title: 'Cart is the bridge to Razorpay-style checkout',
    body: 'The bag in the header opens the cart. Admin, Past orders, and Tour stay in this same header so you can jump without losing the story.',
    tab: 'merchant-checkout',
    view: 'store',
    page: 'store',
    target: 'store-cart-btn',
  },
  {
    id: 'store-cart',
    section: 'Shop',
    lifecycle: 'Shop',
    title: 'Cart total vs what the bank will credit',
    body: 'Subtotal is GMV. The GST line here is 18% on goods for the demo invoice. After capture, Razorpay fee (~2% of GMV) and GST on that fee are deducted before settlement. The merchant does not receive this cart total in the bank.',
    meaning: 'If you expect the cart total to equal the UTR credit, every payment will look like a loss. The controller exists to prove the deductions.',
    action: 'Proceed to checkout when you are ready. The tour will not submit the payment for you.',
    tab: 'merchant-checkout',
    view: 'cart',
    page: 'store',
    target: 'store-cart',
  },
  {
    id: 'store-checkout',
    section: 'Payment',
    lifecycle: 'Payment',
    title: 'Payment — Razorpay Test Mode, not a fake card form',
    body: 'Proceed to checkout opens this pay step. Card, UPI, and netbanking live inside Razorpay’s modal. Plant synthetic row still exists for judges who need a specific break without the modal.',
    meaning: 'Captured means the customer was charged. It does not mean the merchant has been settled. T+2 still has to happen, and the engine still has to agree the arithmetic.',
    action: 'Pick a simulated outcome next. The tour will not open Razorpay for you.',
    tab: 'merchant-checkout',
    view: 'checkout',
    page: 'store',
    target: 'store-checkout',
  },
  {
    id: 'store-outcome',
    section: 'Payment',
    lifecycle: 'Payment',
    title: 'Simulate a clean capture or a known break',
    body: 'Customers never see this control. Use it to plant the break you want to study: missing settlement (no UTR), fee miscalculation, GST line mismatch, unaccounted refund, duplicate, or timing.',
    meaning: 'A flagged payment is not a declined card. The charge succeeded. The books cannot prove the credit, the fee, the tax, or the refund. That is an exception, not a failed checkout.',
    action: 'For the full story pick Fee miscalculation or Missing settlement, then pay after the tour. Clean payment shows the happy path: status matched, no notification.',
    tab: 'merchant-checkout',
    view: 'checkout',
    page: 'store',
    target: 'store-outcome',
    waitFor: 'change',
    tryPrompt: 'Try it: choose Fee miscalculation or Missing settlement.',
  },
  {
    id: 'store-pay',
    section: 'Payment',
    lifecycle: 'Payment',
    title: 'Pay — the tour will not click this',
    body: 'Pay posts the capture into the batch and reconciles that row. If the outcome is a break, you get a warning toast and a controller notification. If it is clean, the row lands as matched on Payments.',
    meaning: 'This is the only moment money is “made”. Everything after this is explanation and matching — Razor-AI never auto-withdraws and never invents a UTR.',
    action: 'After the tour, press Pay yourself. Then use View in Razor-AI or the bell to find the same payment_id.',
    tab: 'merchant-checkout',
    view: 'checkout',
    page: 'store',
    target: 'store-pay',
    lockTarget: true,
  },
  {
    id: 'store-success',
    section: 'Payment',
    lifecycle: 'Payment',
    title: 'Captured — now look at engine outcome',
    body: 'The success screen shows payment_id, method, amount, and whether the engine already called it matched or exception. Settlement can still be pending even when the row matched.',
    meaning: 'If it says exception, the payment is flagged. Open the controller — do not refund from panic, and do not assume the money is lost until you see the mismatch type.',
    action: 'Note the payment_id. Next stop is Past orders (refunds), then Payments in the controller.',
    tab: 'merchant-checkout',
    view: 'success',
    page: 'store',
    target: 'store-success',
    skipUnless: 'lastPayment',
    skipIfMissing: true,
  },
  {
    id: 'store-to-controller',
    section: 'Payment',
    lifecycle: 'Payment',
    title: 'Admin is where flagged payments are worked',
    body: 'Use Admin in this header (or View in Admin after pay). Marketplace stays out of the finance sidebar on purpose — selling and investigating are different jobs.',
    action: 'The next screens are inside the finance controller, starting with the payment register.',
    tab: 'merchant-checkout',
    view: 'store',
    page: 'store',
    target: 'store-to-controller',
  },
  {
    id: 'payments-heading',
    section: 'Payment',
    lifecycle: 'Payment',
    title: 'Payments — every capture in the loaded batch',
    body: 'This table is the source of truth for what was captured. Store checkouts and generated demo rows share one batch. Date filters run on created_at in the backend, not on “today” on your laptop.',
    meaning: 'If a shop payment is missing here, it was not captured (or you are looking at a different batch). If it is here and Unmatched, it is flagged for Exceptions.',
    action: 'Search the payment_id from checkout. Exception rows are clickable — they open the queue.',
    tab: 'dashboard',
    page: 'payments',
    target: 'payments-heading',
  },
  {
    id: 'payments-filter',
    section: 'Payment',
    lifecycle: 'Payment',
    title: 'Narrow by date when the merchant asks “what happened on 14 Aug?”',
    body: 'Presets and custom ranges filter the register. Historical questions in chat use the same idea: the selected day in the books, not calendar today.',
    tab: 'dashboard',
    page: 'payments',
    target: 'payments-filter',
    waitFor: 'filter',
    tryPrompt: 'Try it: click a date preset such as Last 7 days.',
    skipIfMissing: true,
  },
  {
    id: 'payments-rail',
    section: 'Payment',
    lifecycle: 'Payment',
    title: 'All / Matched / Exceptions',
    body: 'Matched means expected settlement equals credited amount after fee, GST and refunds. Exceptions are still open. Counts are batch-wide; the table follows the rail.',
    meaning: 'A flagged payment sits on Exceptions until a human applies an arithmetic fix, waives it, or escalates a missing bank credit. The engine will not silently close it.',
    action: 'Switch to Exceptions on this rail to see only breaks, then open one from the table.',
    tab: 'dashboard',
    page: 'payments',
    target: 'payments-rail',
    skipIfMissing: true,
    waitFor: 'click',
    tryPrompt: 'Try it: click Exceptions on the rail.',
  },
  {
    id: 'payments-table',
    section: 'Payment',
    lifecycle: 'Payment',
    title: 'Read a row: amount, match, settlement',
    body: 'Amount is GMV. Match status is Matched or Unmatched. Settlement is whether a credit is on file. Workflow Unreviewed means a human has not touched the exception yet. There is no extra details button — click the exception row.',
    meaning: 'Settlement empty or missing plus Unmatched is the classic “customer paid, bank line not found” case. Fee/GST breaks often still show a settlement amount that does not equal expected.',
    action: 'Click an Unmatched row after the tour to jump into Exceptions with that payment selected.',
    tab: 'dashboard',
    page: 'payments',
    target: 'payments-table',
  },
  {
    id: 'gst-summary',
    section: 'Fee',
    lifecycle: 'Fee',
    title: 'Fee, then GST — GST is 18% of the processing fee',
    body: 'Razorpay fee is typically 2% of GMV. GST is 18% of that fee, never 18% of GMV. This page compares expected GST (from fee × 18%) with what the batch recorded.',
    meaning: 'If fee is wrong, GST is almost always wrong too. If only GST is off, someone booked tax on the goods value or used the wrong rate. That is a tax-line mismatch, not a missing UTR.',
    action: 'Check Taxable amount (fee) first. If Difference is not zero, click through mismatched lines after this step.',
    tab: 'dashboard',
    page: 'gst',
    target: 'gst-summary',
  },
  {
    id: 'gst-table',
    section: 'Fee',
    lifecycle: 'Fee',
    title: 'Mismatched tax lines open Exceptions',
    body: 'Each line is a payment’s fee and GST. Click a mismatched row to work it in the exception queue. Nothing here is invented to make GST look clean.',
    action: 'Open a mismatched line when you see one. Apply fix is allowed for arithmetic GST; it still will not invent a settlement.',
    tab: 'dashboard',
    page: 'gst',
    target: 'gst-table',
    skipIfMissing: true,
  },
  {
    id: 'store-orders',
    section: 'Refund',
    lifecycle: 'Refund',
    title: 'Refunds start from Past orders, not from the exception queue',
    body: 'A refund is a customer-facing action: it posts refund_amount on the same payment_id, updates cash and GST, and notifies the controller. The tour will not refund for you.',
    meaning: 'If a refund is issued but the batch never received the refund line, reconciliation raises unaccounted refund — settlement looks too high relative to net GMV. If the refund is posted correctly, expected credit falls and the row can still match.',
    action: 'After a checkout, come here to refund. Then re-open Payments / Exceptions for that payment_id. Do not refund to “clear” a missing UTR.',
    tab: 'merchant-checkout',
    view: 'orders',
    page: 'store',
    target: 'store-orders',
    lockTarget: true,
  },
  {
    id: 'cash-position',
    section: 'Settlement',
    lifecycle: 'Settlement',
    title: 'Settlement is T+2 cash — captured is not in the bank yet',
    body: 'Available is matched money whose settled_at has passed. In transit is matched but not yet dated as settled. Blocked / at risk is still sitting on open exceptions. Next 7 days is expected matched inflow.',
    meaning: 'Merchants ask “where is yesterday’s GMV?” The answer is almost never “the AI lost it”. It is in transit, blocked by a flag, refunded, or taken as fee+GST.',
    action: 'Use this page before you withdraw. If at-risk is large, work Exceptions first.',
    tab: 'dashboard',
    page: 'cash',
    target: 'cash-position',
  },
  {
    id: 'cash-why',
    section: 'Settlement',
    lifecycle: 'Settlement',
    title: 'Why is my cash different?',
    body: 'This traces expected GMV down through fee, GST, refunds, in-transit settlements, unresolved exceptions and withdrawals. It only calculates. It does not move money or post a UTR.',
    action: 'Run it after a batch is loaded. Read the waterfall before you chase the bank.',
    tab: 'dashboard',
    page: 'cash',
    target: 'cash-why',
    skipIfMissing: true,
    waitFor: 'click',
    tryPrompt: 'Try it: click Why is my cash different?',
  },
  {
    id: 'reconciliation-generate',
    section: 'Reconciliation',
    lifecycle: 'Reconciliation',
    title: 'Need a full batch? Generate Demo Dataset',
    body: 'Store checkout adds one row. Generate creates a synthetic Razorpay-shaped batch with seeded breaks so you can practice the queue. The tour will not generate a batch for you.',
    meaning: 'Matching is deterministic. Gemini never calculates settlement and never sees the hidden answer key used to score detection.',
    action: 'If Payments is empty, generate 100 rows after the tour, then run the engine.',
    tab: 'dashboard',
    page: 'reconciliation',
    target: 'reconciliation-generate',
    lockTarget: true,
  },
  {
    id: 'reconciliation-run',
    section: 'Reconciliation',
    lifecycle: 'Reconciliation',
    title: 'Run reconciliation — expected vs credited',
    body: 'expected = amount − fee − tax − refund. Fee must be 2% of GMV. GST must be 18% of fee. Missing settlement_id stays an exception. Malformed CSV rows are kept and flagged, not dropped.',
    meaning: 'This is the moment rows become Matched or Exception. Re-running after a store payment updates that new row too.',
    action: 'Run it yourself when a batch is loaded. Then read Matched vs Needs attention on the right.',
    tab: 'dashboard',
    page: 'reconciliation',
    target: 'reconciliation-run',
    lockTarget: true,
  },
  {
    id: 'reconciliation-results',
    section: 'Reconciliation',
    lifecycle: 'Reconciliation',
    title: 'Throughput, matched amount, honest leftovers',
    body: 'Matched rupees, active batch, and needs-attention count come from the engine. Accuracy against the seed key is reported on Reports — you cannot hide leftovers by resolving them after the fact on that score.',
    action: 'If needs-attention is above zero, go to Exceptions. That is the product, not a failure of the demo.',
    tab: 'dashboard',
    page: 'reconciliation',
    target: 'reconciliation-results',
  },
  {
    id: 'exceptions-list',
    section: 'Exception',
    lifecycle: 'Exception',
    title: 'A flagged payment lands here — this is the queue',
    body: 'Each row is a payment the engine could not confidently close. Priority: Critical = missing settlement ≥ ₹2,000; High = missing below that or a large delta; Medium = fee / GST / refund / partial; Low = timing with ~₹0 delta.',
    meaning: 'Flagged means “books do not prove this credit”, not “fraud confirmed” and not “payment failed”. Duplicate in this demo means the same payment_id appeared twice in the batch.',
    action: 'Click a payment ID. Read mismatch type before you touch Actions. Filter by type if you are hunting a fee vs a missing UTR.',
    tab: 'dashboard',
    page: 'exceptions',
    target: 'exceptions-list',
    waitFor: 'click',
    tryPrompt: 'Try it: click a payment ID in the table.',
  },
  {
    id: 'exceptions-filter',
    section: 'Exception',
    lifecycle: 'Exception',
    title: 'Filter by mismatch type and date',
    body: 'Search payment ID or explanation. Type filter isolates fee miscalculation, GST, unaccounted refund, missing settlement, duplicate, timing, partial. Unreviewed vs all trades is the left rail.',
    action: 'When a merchant says “GST is off”, set the type filter instead of scrolling. Re-run engine only after new ingest or checkout.',
    tab: 'dashboard',
    page: 'exceptions',
    target: 'exceptions-filter',
  },
  {
    id: 'notifications',
    section: 'Exception',
    lifecycle: 'Exception',
    title: 'The bell is how a live checkout taps you on the shoulder',
    body: 'Flagged store payments and refunds appear here with mismatch type, priority, and which page to open. Clicking a notification jumps to Exceptions, GST, Payments or Withdraw as appropriate.',
    meaning: 'You do not have to hunt the table after every shop order. The notification is the same engine result, not a second opinion from the model.',
    action: 'After you pay with a planted break, open the bell first. Mark all read only when you have actually looked.',
    tab: 'dashboard',
    page: 'home',
    target: 'notifications',
    openNotifications: true,
    skipIfMissing: true,
  },
  {
    id: 'exception-ledger',
    section: 'Investigation',
    lifecycle: 'Investigation',
    title: 'Investigation starts with the ledger strip',
    body: 'Gross, settlement, fee, GST, refund, and the suggested action are the facts. Diagnosis is the rule-engine explanation. Evidence ticks show which signals passed or gapped (settlement present, fee rate, tax rate, refund recorded).',
    meaning: 'If settlement is missing, stop — you cannot arithmetic-fix a hole in the bank file. If fee/GST/refund numbers disagree, the waterfall will show where the rupees went.',
    action: 'Read evidence before Actions. Next: Explain this difference, then Investigate exception.',
    tab: 'dashboard',
    page: 'exceptions',
    target: 'exception-ledger',
    panel: 'details',
    safeSelect: true,
    skipIfMissing: true,
  },
  {
    id: 'exception-explain',
    section: 'Investigation',
    lifecycle: 'Investigation',
    title: 'Explain this difference — GMV → fee → GST → refund → credited',
    body: 'The waterfall is read-only. It subtracts known deductions from GMV and compares to what was credited. Unexplained remainder stays visible. Gemini is not doing this math.',
    meaning: 'If the waterfall fully explains the credit, the break is classification/timing and a human can apply the suggested arithmetic fix. If a step is Missing, that is usually a settlement or refund document you still need.',
    action: 'Click Explain this difference on a selected exception. Then decide: fix, escalate, or keep investigating.',
    tab: 'dashboard',
    page: 'exceptions',
    target: 'exception-explain',
    panel: 'details',
    safeSelect: true,
    waitFor: 'click',
    tryPrompt: 'Try it: click Explain this difference.',
    skipIfMissing: true,
  },
  {
    id: 'exception-investigate',
    section: 'Investigation',
    lifecycle: 'Investigation',
    title: 'Investigate exception — deterministic scan, no invented evidence',
    body: 'Investigate pulls related records and names a most-likely cause with a recommended action. It will not fabricate a UTR, a bank statement, or a customer complaint.',
    meaning: 'Use this when the waterfall is not enough: duplicate rows, timing vs missing, refund posted in store but not in the export. The AI note is commentary on retrieved JSON, not a second ledger.',
    action: 'Click Investigate exception. If the cause is missing settlement, your job is to chase the UTR — not to waive it away without a note.',
    tab: 'dashboard',
    page: 'exceptions',
    target: 'exception-investigate',
    panel: 'details',
    safeSelect: true,
    waitFor: 'click',
    tryPrompt: 'Try it: click Investigate exception.',
    skipIfMissing: true,
  },
  {
    id: 'exception-resolve',
    section: 'Resolution',
    lifecycle: 'Resolution',
    title: 'Human resolution — the tour will not click these',
    body: 'Apply suggested fix: only when the type is auto-fixable (fee, GST, some refund/timing arithmetic). Missing settlement shows Human review required. Acknowledge = still open. Escalate = keep on the honest list. Waive = human override, audited, still no invented UTR. Reject / Reopen / Add note are the rest of the workdesk.',
    meaning: 'Razor-AI’s promise is the leftover list stays honest. Auto-fixing a missing bank credit would be a lie. Waiving without reading evidence creates cash you do not have.',
    action: 'After the tour: apply fix on a fee/GST row and watch it leave the open queue. On a missing UTR, escalate. Close books from the top bar only when you accept the remainder.',
    tab: 'dashboard',
    page: 'exceptions',
    target: 'exception-resolve',
    panel: 'actions',
    safeSelect: true,
    skipIfMissing: true,
    lockTarget: true,
  },
  {
    id: 'dashboard-overview',
    section: 'Home',
    title: 'Controller home — after the loop, this is the daily desk',
    body: 'Match rate, open exceptions, and cash sit together so a controller does not live only in the queue. Load a batch from Reconciliation if the desk is empty.',
    tab: 'dashboard',
    page: 'home',
    target: 'dashboard-overview',
  },
  {
    id: 'dashboard-metrics',
    section: 'Home',
    title: 'Match rate is measured, not generated',
    body: 'These KPIs come from the last engine run. They move when you generate, checkout, refund, apply a fix, or close books — not when chat answers a question.',
    tab: 'dashboard',
    page: 'home',
    target: 'dashboard-metrics',
  },
  {
    id: 'dashboard-queue',
    section: 'Home',
    title: 'Work queue ranks what to do next',
    body: 'High-value missing settlements, recurring clusters, GST mismatches — ranked from live data. Click a row to open that exception.',
    tab: 'dashboard',
    page: 'home',
    target: 'dashboard-queue',
    skipIfMissing: true,
  },
  {
    id: 'dashboard-cash',
    section: 'Home',
    title: 'Cash strip on home is the same T+2 picture',
    body: 'Jump to Cash for the full forecast. Do not withdraw from this strip; Withdraw is a separate, explicit confirmation.',
    tab: 'dashboard',
    page: 'home',
    target: 'dashboard-cash',
    skipIfMissing: true,
  },
  {
    id: 'settlement-qa',
    section: 'Q&A',
    title: 'Ask about a day or this batch — Gemini only explains verified JSON',
    body: 'Questions like “What happened on 14 Aug?”, “Why was the settlement lower?”, and “Show unresolved exceptions from this batch” run tools on filtered rows first. The model does not invent payment_ids or UTRs.',
    action: 'Set the inquiry date from Summary if you are in a historical batch. Never paste .env or customer PII into chat.',
    tab: 'dashboard',
    page: 'home',
    target: 'settlement-qa',
    skipIfMissing: true,
  },
  {
    id: 'withdraw-available',
    section: 'Withdraw',
    title: 'Withdraw only what is eligible',
    body: 'Available excludes in-transit, blocked exceptions, and amounts already withdrawn. Preview breaks out fees, tax and refunds. Confirming writes a synthetic ledger withdrawal — not a real bank payout.',
    tab: 'dashboard',
    page: 'withdraw',
    target: 'withdraw-available',
  },
  {
    id: 'withdraw-confirm',
    section: 'Withdraw',
    title: 'Confirm withdrawal — try this yourself',
    body: 'The tour will not press Confirm. If you do, cash updates and an audit row is written.',
    tab: 'dashboard',
    page: 'withdraw',
    target: 'withdraw-confirm',
    skipIfMissing: true,
    lockTarget: true,
  },
  {
    id: 'audit-table',
    section: 'Audit logs',
    title: 'Every human and engine action is kept',
    body: 'Applies, waives, escalations, notes, withdrawals, Gemini Q&A. Click a row for the record_id and payload. This is how you prove a waive did not invent a UTR.',
    tab: 'dashboard',
    page: 'audit',
    target: 'audit-table',
  },
  {
    id: 'rules-purpose',
    section: 'Rules',
    title: 'Rules are investigator policy, not auto-posting',
    body: 'Write what a human should check for a mismatch type. Investigation text may quote a rule. Rules never auto-fix books or mint a settlement.',
    tab: 'dashboard',
    page: 'knowledge',
    target: 'rules-purpose',
  },
  {
    id: 'reports-period',
    section: 'Reports',
    title: 'Close report and engine validation',
    body: 'Charts are GMV, GST and net settlement from the active batch. Validation shows seeded vs detected vs false positives. Download Word after Close books.',
    tab: 'dashboard',
    page: 'reports',
    target: 'reports-period',
    skipIfMissing: true,
  },
];

export const TOUR_SECTIONS = [...new Set(TOUR_STEPS.map((step) => step.section))];

export const JOURNEY = [
  {
    section: 'Shop',
    title: 'Shop',
    body: 'Add products in Northwind Goods. Nothing is in the books until you pay.',
  },
  {
    section: 'Payment',
    title: 'Payment',
    body: 'Capture on UPI, card or netbanking. Plant a clean row or a known break. Find it on Payments.',
  },
  {
    section: 'Fee',
    title: 'Fee & GST',
    body: 'Fee is ~2% of GMV. GST is 18% of the fee. Wrong fee or tax becomes a flag, not a failed payment.',
  },
  {
    section: 'Refund',
    title: 'Refund',
    body: 'Refund from Past orders. The same payment_id updates cash, GST and the engine.',
  },
  {
    section: 'Settlement',
    title: 'Settlement',
    body: 'Captured ≠ settled. Cash shows available, T+2 in-transit, and amount blocked by exceptions.',
  },
  {
    section: 'Reconciliation',
    title: 'Reconciliation',
    body: 'expected = amount − fee − tax − refund. Matching is deterministic. Gemini is only for Q&A.',
  },
  {
    section: 'Exception',
    title: 'Exception',
    body: 'Flagged means the books cannot prove the credit. Priority tells you what to work first.',
  },
  {
    section: 'Investigation',
    title: 'Investigation',
    body: 'Read evidence, run the GMV waterfall, then Investigate. No invented UTR.',
  },
  {
    section: 'Resolution',
    title: 'Human resolution',
    body: 'Apply arithmetic fixes. Escalate missing settlements. Waive only with a note. Close books when you accept the remainder.',
  },
];

export function firstStepIndexForPage(page, tab = 'dashboard') {
  if (tab === 'merchant-checkout') {
    const view = page || 'store';
    const exact = TOUR_STEPS.findIndex((step) => step.tab === 'merchant-checkout' && (step.view || 'store') === view);
    if (exact >= 0) return exact;
    const store = TOUR_STEPS.findIndex((step) => step.tab === 'merchant-checkout');
    return store >= 0 ? store : 0;
  }
  const index = TOUR_STEPS.findIndex((step) => step.page === page);
  return index >= 0 ? index : 0;
}

export function firstStepIndexForSection(section) {
  const index = TOUR_STEPS.findIndex((step) => step.section === section);
  return index >= 0 ? index : 0;
}

export const STORAGE_KEY = 'razorai-product-tour';
